### ISSUE TITLE
Unable to create package on Mac

### ISSUE THREAD

**Issue by evanwalsh** [joaomoreno/gulp-atom-electron#21]
Every time I try to package my app with the latest version (0.12.0), I get an error like this:

```
↓ electron-v0.26.1-darwin-x64.zip [===-----------------] 13%buffer.js:68
    throw new TypeError('must start with number, buffer, array or string');
    ^
TypeError: must start with number, buffer, array or string
    at new Buffer (buffer.js:68:11)
    at DestroyableTransform.through.obj.stream.push.File.path [as _transform] (/Users/evan/code/javascript/neonsolitude/node_modules/gulp-atom-electron/node_modules/gulp-vinyl-zip/lib/zip/index.js:24:21)
    at DestroyableTransform.Transform._read (/Users/evan/code/javascript/neonsolitude/node_modules/gulp-atom-electron/node_modules/gulp-vinyl-zip/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/evan/code/javascript/neonsolitude/node_modules/gulp-atom-electron/node_modules/gulp-vinyl-zip/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/evan/code/javascript/neonsolitude/node_modules/gulp-atom-electron/node_modules/gulp-vinyl-zip/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/evan/code/javascript/neonsolitude/node_modules/gulp-atom-electron/node_modules/gulp-vinyl-zip/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/Users/evan/code/javascript/neonsolitude/node_modules/gulp-atom-electron/node_modules/gulp-vinyl-zip/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at DestroyableTransform._transform (/Users/evan/code/javascript/neonsolitude/node_modules/gulp-atom-electron/node_modules/gulp-vinyl-zip/lib/dest/index.js:13:9)
    at DestroyableTransform.Transform._read (/Users/evan/code/javascript/neonsolitude/node_modules/gulp-atom-electron/node_modules/gulp-vinyl-zip/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/evan/code/javascript/neonsolitude/node_modules/gulp-atom-electron/node_modules/gulp-vinyl-zip/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/evan/code/javascript/neonsolitude/node_modules/gulp-atom-electron/node_modules/gulp-vinyl-zip/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/evan/code/javascript/neonsolitude/node_modules/gulp-atom-electron/node_modules/gulp-vinyl-zip/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
```

The download progress always stops, but never at the same percentage. I thought it was a problem with my network, but nothing I change on my end fixes it.

My gulp task looks like this:

```js
gulp.task('package:mac', function() {
  return gulp.src(['./**/*', '!./build'])
    .pipe(electron({
      version: '0.26.1',
      platform: 'darwin'
    }))
    .pipe(electron.zfsdest('./build/mac.zip');
});
```

I also tried adding a GitHub token, but that didn't change anything.

**Comment by joaomoreno** [comment]
Do you happen to have any symlinks among the files you are sourcing in `gulp.src`?

**Comment by evanwalsh** [comment]
@joaomoreno I didn't think I did, but I had one lurking in there because I had installed `electron-prebuilt` as a dependency before. Removing that fixed it. Thanks!
