### ISSUE TITLE
Typo in readme ?

### ISSUE THREAD

**Issue by Bewi** [joaomoreno/gulp-atom-electron#25]
In Readme, Usage section, looks like there is a typo for the configuration of the destination.
At the moment it is **electron.dest**, which is not working.
Shouldn't it be **gulp.dest** instead ?

**Comment by joaomoreno** [comment]
I can't reproduce `electron.dest` not working. It does work for me.

You need to use a special `dest` function which takes care of creating the Electron's symlinks on OS X. `gulp.dest` will fail at that.

**Comment by mdekrey** [comment]
Unfortunately, I'm going to have to agree with @Bewi; I'm getting an error following the instructions from the readme, too.

I'm getting this error when trying to run my gulpfile:

    [09:56:51] TypeError: Cannot read property 'platform' of undefined
        at Function.dest (/Users/xxx/node_modules/gulp-atom-electron/src/index.js:104:22)
        at Gulp.<anonymous> (/Users/xxx/gulpfile.js:349:20)
        at module.exports (/Users/xxx/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
        at Gulp.Orchestrator._runTask (/Users/xxx/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
        at Gulp.Orchestrator._runStep (/Users/xxx/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
        at Gulp.Orchestrator.start (/Users/xxx/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
        at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
        at process._tickCallback (node.js:355:11)
        at Function.Module.runMain (module.js:503:11)
        at startup (node.js:129:16)
        at node.js:814:3

My gulp task matches the Readme.md:

    gulp.task('electronOsxApp', function () {
      return gulp.src('src/**')
        .pipe(electron({ version: '0.33.7', platform: 'darwin' }))
        .pipe(electron.dest(electronAppPath));
    });

My package.json specifies my version as:

    "gulp-atom-electron": "0.17.2",

I believe, due to the following line, `dest` now requires a second parameter, which is giving the above error message:
https://github.com/joaomoreno/gulp-atom-electron/blob/6da5829db6886602bfb869f404da94487eb7e62e/src/index.js#L104

**Comment by joaomoreno** [comment]
I can reproduce. Working on a fix!

**Comment by joaomoreno** [comment]
Fixed! Also improved the docs quite a bit. Thanks for the help guys. :beers:
