### ISSUE TITLE
Error handling is broken

### ISSUE THREAD

**Issue by joaomoreno** [joaomoreno/gulp-atom-electron#66]
@sbatten 

```
$ /__w/1/s/node_modules/.bin/npm-run-all -lp 'electron x64' playwright-install
[electron x64      ] $ node build/lib/electron x64
[electron x64      ] (node:11811) UnhandledPromiseRejectionWarning: HttpError: Not Found
[electron x64      ]     at /__w/1/s/node_modules/@octokit/request/dist-node/index.js:66:23
[electron x64      ]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[electron x64      ]     at async getDownloadUrl (/__w/1/s/node_modules/gulp-atom-electron/src/util.js:15:28)
[electron x64      ] (node:11811) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[electron x64      ] (node:11811) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[electron x64      ] (node:11811) UnhandledPromiseRejectionWarning: HttpError: Not Found
[electron x64      ]     at /__w/1/s/node_modules/@octokit/request/dist-node/index.js:66:23
[electron x64      ]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[electron x64      ]     at async getDownloadUrl (/__w/1/s/node_modules/gulp-atom-electron/src/util.js:15:28)
[electron x64      ] (node:11811) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
Finishing: Download Electron and Playwright
```

The `download` stream doens't throw an error. It just spits out an unhandled promise reject warning and acts as if nothing has happened.

**Comment by joaomoreno** [comment]
Omg something is seriously broken with this. Using any version  of this module over 1.22.0 in microsoft/vscode just breaks everything. I spent two hours trying to investigate this and couldn't find why. I give up.
